// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use DIRECT_URL for migrations/schema push (required for DDL operations)
    // For runtime queries with pooling, use DATABASE_URL in your app
    url: process.env["DIRECT_URL"],
  },
});
